import { ProjectDetailsFileSystemModals } from './ProjectDetailsFileSystemModals'
import { ProjectDetailsContent } from './ProjectDetailsContent'
import { ProjectDetailsErrorView, ProjectDetailsLoadingView } from './ProjectDetailsStateViews'
import { ProjectDetailsOverlays } from './ProjectDetailsOverlays'
import { ProjectDetailsTransientUi } from './ProjectDetailsTransientUi'
import { buildProjectDetailsShell } from './projectDetailsShell'
import {
    buildProjectDetailsContentProps,
    buildProjectDetailsFileSystemModalProps,
    buildProjectDetailsOverlayProps,
    buildProjectDetailsTransientUiProps
} from './projectDetailsPageViewProps'

export function ProjectDetailsPageView(props: any) {
    const {
        loading,
        project,
        error,
        navigate,
        decodedPath,
        isCondensedLayout,
        themeColor,
        showScriptsModal,
        setShowScriptsModal,
        showDependenciesModal,
        setShowDependenciesModal,
        loadProjectDetails,
        runScript,
        scriptPredictions,
        selectedCommit,
        commitDiff,
        loadingDiff,
        setSelectedCommit,
        setCommitDiff,
        showAuthorMismatch,
        gitUser,
        repoOwner,
        handleAuthorMismatchConfirm,
        setShowAuthorMismatch,
        settings,
        updateSettings,
        showInitModal,
        setShowInitModal,
        setInitStep,
        initStep,
        branchName,
        setBranchName,
        customBranchName,
        setCustomBranchName,
        createGitignore,
        setCreateGitignore,
        gitignoreTemplate,
        setGitignoreTemplate,
        availableTemplates,
        availablePatterns,
        selectedPatterns,
        setSelectedPatterns,
        patternSearch,
        setPatternSearch,
        createInitialCommit,
        setCreateInitialCommit,
        initialCommitMessage,
        setInitialCommitMessage,
        isInitializing,
        handleInitGit,
        remoteUrl,
        setRemoteUrl,
        isAddingRemote,
        handleAddRemote,
        handleSkipRemote,
        isProjectLive,
        activePorts,
        formatRelTime,
        openTerminal,
        projectTerminalLabel,
        projectRootPath,
        showToast,
        handleCopyPath,
        copiedPath,
        handleOpenInExplorer,
        goBack,
        activeTab,
        setActiveTab,
        fileTree,
        loadingGit,
        loadingGitHistory,
        loadingFiles,
        changedFiles,
        stagedFiles,
        unstagedFiles,
        unpushedCommits,
        readmeContentRef,
        readmeExpanded,
        readmeNeedsExpand,
        setReadmeExpanded,
        fileSearch,
        setFileSearch,
        setIsExpandingFolders,
        expandedFolders,
        setExpandedFolders,
        loadingFolderPaths,
        allFolderPathsSet,
        isExpandingFolders,
        showHidden,
        setShowHidden,
        sortBy,
        setSortBy,
        sortAsc,
        setSortAsc,
        visibleFileList,
        openPreview,
        handleFileTreeOpen,
        handleToggleFolder,
        handleToggleAllFolders,
        handleFileTreeOpenWith,
        handleFileTreeOpenInExplorer,
        handleFileTreeCopyPath,
        handleFileTreeCopy,
        handleFileTreeRename,
        handleFileTreeDelete,
        handleFileTreePaste,
        handleFileTreeMove,
        handleFileTreeCreateFile,
        handleFileTreeCreateFolder,
        fileClipboardItem,
        gitError,
        gitView,
        setGitView,
        refreshGitData,
        isGitRepo,
        currentBranch,
        targetBranch,
        setTargetBranch,
        branches,
        isSwitchingBranch,
        handleSwitchBranch,
        commitMessage,
        setCommitMessage,
        handleGenerateCommitMessage,
        isGeneratingCommitMessage,
        isCommitting,
        isStackedActionRunning,
        handleCommit,
        handleCommitPushAndCreatePullRequest,
        handleDangerouslyStageCommitPushAndCreatePullRequest,
        handleStageFile,
        handleUnstageFile,
        handleStageAll,
        handleUnstageAll,
        handleDiscardUnstagedFile,
        handleDiscardUnstagedAll,
        ensureWorkingChangeStats,
        hasRemote,
        gitSyncStatus,
        incomingCommits,
        handleFetch,
        handlePush,
        handlePull,
        isPushing,
        isFetching,
        isPulling,
        lastFetched,
        lastPulled,
        gitHistory,
        gitHistoryTotalCount,
        historyHasMore,
        loadingMoreHistory,
        loadMoreGitHistory,
        remotes,
        tags,
        stashes,
        changesPage,
        setChangesPage,
        ITEMS_PER_PAGE,
        handleCommitClick,
        unpushedPage,
        setUnpushedPage,
        pullsPage,
        setPullsPage,
        COMMITS_PER_PAGE,
        commitPage,
        setCommitPage,
        scriptIntentContext,
        pendingScriptRun,
        scriptPortInput,
        setScriptPortInput,
        setScriptRunError,
        scriptExposeNetwork,
        setScriptExposeNetwork,
        scriptAdvancedOpen,
        setScriptAdvancedOpen,
        scriptExtraArgsInput,
        setScriptExtraArgsInput,
        scriptEnvInput,
        setScriptEnvInput,
        scriptRunError,
        scriptCommandPreview,
        scriptRunner,
        closeScriptRunModal,
        handleConfirmScriptRun,
        previewFile,
        previewMediaItems,
        previewContent,
        loadingPreview,
        previewTruncated,
        previewSize,
        previewBytes,
        previewModifiedAt,
        refreshVisibleFileTree,
        closePreview,
        toast,
        setToast,
        createTarget,
        createErrorMessage,
        submitCreateTarget,
        setCreateTarget,
        createDraft,
        setCreateDraft,
        setCreateErrorMessage,
        renameTarget,
        renameDraft,
        setRenameDraft,
        renameErrorMessage,
        submitRenameTarget,
        setRenameTarget,
        setRenameExtensionSuffix,
        renameExtensionSuffix,
        setRenameErrorMessage,
        deleteTarget,
        confirmDeleteTarget,
        setDeleteTarget
    } = props

    const fallbackProjectPath = String(decodedPath || '').trim()
    const displayProject = project ?? (fallbackProjectPath ? buildProjectDetailsShell(fallbackProjectPath) : null)
    const progressiveProps = displayProject
        ? {
            ...props,
            project: displayProject,
            projectDetailsLoading: loading
        }
        : props

    if (loading && !displayProject) {
        return <ProjectDetailsLoadingView />
    }
    if (!project) {
        if (!loading && error) {
            return <ProjectDetailsErrorView error={error} onBackToProjects={() => navigate('/projects')} />
        }
        if (!displayProject) {
            return <ProjectDetailsLoadingView />
        }
    }

    return (
        <div
            className={isCondensedLayout
                ? 'animate-fadeIn pb-24 pl-6 pt-6 pr-6 transition-[width,margin-right,padding] duration-300 ease-[cubic-bezier(0.4,0,0.2,1)]'
                : 'mx-auto animate-fadeIn pb-24 px-6 pt-6 transition-[max-width,padding] duration-300 ease-[cubic-bezier(0.4,0,0.2,1)]'}
            style={{
                maxWidth: isCondensedLayout ? undefined : '1600px'
            }}
        >
            <ProjectDetailsOverlays {...buildProjectDetailsOverlayProps(progressiveProps)} />
            <ProjectDetailsContent {...buildProjectDetailsContentProps(progressiveProps)} />
            <ProjectDetailsTransientUi {...buildProjectDetailsTransientUiProps(progressiveProps)} />
            <ProjectDetailsFileSystemModals {...buildProjectDetailsFileSystemModalProps(progressiveProps)} />
        </div>
    )
}
