import type { ToolDefinition } from '../types'

export const AI_AGENT_TOOLS_B: ToolDefinition[] = [
    {
                id: 'gpt-engineer',
                command: 'gpte',
                displayName: 'GPT Engineer',
                description: 'GPT Engineer is an AI agent that generates entire codebases from a prompt. Specify what you want to build and it creates the complete project structure.',
                themeColor: '#10B981',
                icon: 'python',
                website: 'https://gptengineer.app',
                docsUrl: 'https://github.com/gpt-engineer-org/gpt-engineer',
                category: 'ai_agent',
                usedFor: ['ai', 'coding', 'generation', 'scaffolding'],
                capabilities: ['Project Generation', 'Rapid Scaffolding', 'Prompt to Code'],
                alternateCommands: ['gpt-engineer'],
                installCommand: 'python -m pip install gpt-engineer',
                startupCommand: 'gpte',
                versionCheckCommand: 'pip show gpt-engineer',
                updateCommand: 'python -m pip install -U gpt-engineer',
                logoUrl: 'https://raw.githubusercontent.com/gpt-engineer-org/gpt-engineer/main/assets/logo.png'
            },

    {
                id: 'plandex',
                command: 'plandex',
                displayName: 'Plandex',
                description: 'Plandex is an open-source, terminal-based AI coding engine. it can handle complex, multi-stage tasks that span many files and directories, with a focus on reliability and developer control.',
                themeColor: '#6366F1',
                icon: 'gnubash',
                website: 'https://plandex.ai',
                docsUrl: 'https://github.com/plandex-ai/plandex',
                category: 'ai_agent',
                usedFor: ['ai', 'coding', 'terminal', 'multi-file'],
                capabilities: ['Complex Tasks', 'Multi-file Editing', 'Terminal Based'],
                installCommand: 'curl -sL https://plandex.ai/install.sh | bash',
                startupCommand: 'plandex',
                versionCheckCommand: 'plandex version',
                updateCommand: 'curl -sL https://plandex.ai/install.sh | bash',
                logoUrl: 'https://plandex.ai/favicon.ico'
            },

    {
                id: 'openhands',
                command: 'openhands',
                displayName: 'OpenHands',
                description: 'OpenHands (formerly OpenDevin) is an open-source platform for AI software agents. It aims to build agents that can interact with the world by writing code, using the terminal, and browsing the web.',
                themeColor: '#2563EB',
                icon: 'docker',
                website: 'https://github.com/All-Hands-AI/OpenHands',
                docsUrl: 'https://all-hands-ai.github.io/OpenHands/',
                category: 'ai_agent',
                usedFor: ['ai', 'coding', 'automation', 'open-source'],
                capabilities: ['Autonomous Coding', 'Web Browsing', 'Terminal Access'],
                installCommand: 'uv tool install openhands --python 3.12',
                startupCommand: 'openhands',
                versionCheckCommand: 'openhands --version',
                updateCommand: 'pip install -U openhands-ai openhands',
                logoUrl: 'https://raw.githubusercontent.com/All-Hands-AI/OpenHands/main/docs/static/img/logo.png'
            },

    {
                id: 'supermaven',
                command: 'supermaven',
                displayName: 'Supermaven',
                description: 'Supermaven is an ultra-fast AI code completion tool with a 1-million-token context window. It provides near-instant suggestions and understands your entire codebase.',
                themeColor: '#F59E0B',
                icon: '',  // Supermaven not on simpleicons
                website: 'https://supermaven.com',
                docsUrl: 'https://supermaven.com/docs',
                category: 'ai_agent',
                usedFor: ['ai', 'coding', 'autocomplete', 'fast'],
                capabilities: ['Huge Context', 'Ultra Fast', 'IDE Native'],
                installCommand: 'Install "Supermaven" extension in VS Code/JetBrains',
                startupCommand: 'code (via Extension)',
                versionCheckCommand: 'N/A (Extension)',
                updateCommand: 'Extension auto-updates',
                logoUrl: 'https://supermaven.com/favicon.ico'
            },

    {
                id: 'phind',
                command: 'phind',
                displayName: 'Phind',
                description: 'Phind is an intelligent search engine and pair programmer for developers. It combines the power of LLMs with real-time web search to provide accurate answers and code examples.',
                themeColor: '#6366F1',
                icon: '',  // Phind not on simpleicons
                website: 'https://phind.com',
                docsUrl: 'https://phind.com/docs',
                category: 'ai_agent',
                usedFor: ['ai', 'search', 'coding', 'pair-programming'],
                capabilities: ['AI Search', 'Code Generation', 'Web Integrated'],
                installCommand: 'Install "Phind" extension in VS Code',
                startupCommand: 'code (via Extension)',
                versionCheckCommand: 'N/A (Web/Extension)',
                updateCommand: 'Extension auto-updates',
                logoUrl: 'https://phind.com/images/logo-small.png'
            },

    {
                id: 'sweep',
                command: 'sweep',
                displayName: 'Sweep',
                description: 'Sweep is an AI junior developer that turns GitHub issues into pull requests. It reads your codebase, plans changes, and writes code to fix bugs and implement features.',
                themeColor: '#7C3AED',
                icon: 'github',
                website: 'https://sweep.dev',
                docsUrl: 'https://docs.sweep.dev',
                category: 'ai_agent',
                usedFor: ['ai', 'coding', 'github', 'automation'],
                capabilities: ['Issue to PR', 'Automated Bug Fix', 'Github Native'],
                installCommand: 'pip install sweepai',
                startupCommand: 'sweep (or GitHub App)',
                versionCheckCommand: 'sweep --version',
                updateCommand: 'pip install --upgrade sweepai',
                logoUrl: 'https://avatars.githubusercontent.com/u/108284566'
            },

    {
                id: 'gemini-cli',
                command: 'gemini',
                displayName: 'Gemini CLI',
                description: 'Gemini CLI is Google\'s AI-powered command-line tool that brings Gemini directly to your terminal. It can help with coding, answer questions, and assist with various development tasks.',
                themeColor: '#4285F4',
                icon: 'googlegemini',
                website: 'https://github.com/google-gemini/gemini-cli',
                docsUrl: 'https://github.com/google-gemini/gemini-cli',
                category: 'ai_agent',
                usedFor: ['ai', 'coding', 'terminal', 'google'],
                capabilities: ['Gemini AI', 'Terminal Native', 'Code Assistance'],
                installCommand: 'npm install -g @google/gemini-cli',
                startupCommand: 'gemini',
                versionCheckCommand: 'gemini --version',
                updateCommand: 'npm install -g @google/gemini-cli@latest',
                logoUrl: 'https://lh3.googleusercontent.com/X-LdC6qj-i8j8-5x9x9x9x9x9x9x9x9x9x9x9x9x9x9x9x9x9x9x9x9x9x9x9x9x9=s0'
            },

    {
                id: 'opencode',
                command: 'opencode',
                displayName: 'OpenCode',
                description: 'OpenCode is a terminal-based AI coding assistant. It provides an interactive coding experience with AI assistance directly in your terminal.',
                themeColor: '#10B981',
                icon: 'gnubash',
                website: 'https://github.com/opencode-ai/opencode',
                docsUrl: 'https://github.com/opencode-ai/opencode',
                category: 'ai_agent',
                usedFor: ['ai', 'coding', 'terminal', 'open-source'],
                capabilities: ['Terminal UI', 'Code Editing', 'Open Source'],
                installCommand: 'curl -fsSL https://opencode.ai/install | bash',
                startupCommand: 'opencode',
                versionCheckCommand: 'opencode --version',
                updateCommand: 'opencode upgrade',
                logoUrl: 'https://opencode.ai/favicon.ico'
            },

    {
                id: 'droid',
                command: 'droid',
                displayName: 'Factory Droid',
                description: 'Factory Droid is an enterprise-grade AI coding agent that lives in your terminal. It handles end-to-end development workflows, understands your codebase, and integrates with tools like Jira, Notion, and Slack.',
                themeColor: '#6366F1',
                icon: 'android',
                website: 'https://factory.ai',
                docsUrl: 'https://docs.factory.ai',
                category: 'ai_agent',
                usedFor: ['ai', 'coding', 'terminal', 'enterprise'],
                capabilities: ['Agentic Coding', 'Enterprise Integration', 'Multi-file Edits'],
                installCommand: 'curl -fsSL https://app.factory.ai/cli | sh',
                startupCommand: 'droid',
                versionCheckCommand: 'droid --version',
                updateCommand: 'curl -fsSL https://app.factory.ai/cli | sh',
                logoUrl: 'https://factory.ai/favicon.ico'
            },

    {
                id: 'codex-cli',
                command: 'codex',
                displayName: 'Codex CLI',
                description: 'Codex CLI is OpenAI\'s command-line coding assistant. It brings the power of OpenAI models to your terminal for code generation and assistance.',
                themeColor: '#10A37F',
                icon: 'openai',
                website: 'https://github.com/openai/codex-cli',
                docsUrl: 'https://github.com/openai/codex-cli',
                category: 'ai_agent',
                usedFor: ['ai', 'coding', 'terminal', 'openai'],
                capabilities: ['OpenAI Models', 'Code Generation', 'Terminal Native'],
                installCommand: 'npm install -g @openai/codex',
                startupCommand: 'codex',
                versionCheckCommand: 'codex --version',
                updateCommand: 'npm install -g @openai/codex',
                logoUrl: 'https://openai.com/favicon.ico'
            },

    {
                id: 'amazon-q',
                command: 'q',
                displayName: 'Amazon Q Developer',
                description: 'Amazon Q Developer is AWS\'s AI-powered assistant for software development. It provides code suggestions, answers questions, and helps with AWS services.',
                themeColor: '#FF9900',
                icon: 'amazonaws',
                website: 'https://aws.amazon.com/q/developer/',
                docsUrl: 'https://docs.aws.amazon.com/amazonq/',
                category: 'ai_agent',
                usedFor: ['ai', 'coding', 'aws', 'cloud'],
                capabilities: ['AWS Integration', 'Code Suggestions', 'Cloud Native'],
                installCommand: 'brew install --cask amazon-q (macOS) / Download from aws.amazon.com',
                startupCommand: 'q',
                versionCheckCommand: 'q --version',
                updateCommand: 'Auto-updates (or re-run installer)',
                logoUrl: 'https://d1.awsstatic.com/r2020/q/product-page/Amazon-Q_Icon_64x64.png'
            },

    {
                id: 'amp',
                command: 'amp',
                displayName: 'Amp',
                description: 'Amp is a frontier coding agent by Sourcegraph that lets you wield the full power of leading models. Use it from your terminal with the CLI or as a VS Code extension.',
                themeColor: '#FF6B6B',
                icon: 'sourcegraph',
                website: 'https://ampcode.com',
                docsUrl: 'https://ampcode.com',
                category: 'ai_agent',
                usedFor: ['ai', 'coding', 'terminal', 'agentic-flow'],
                capabilities: ['Agentic Coding', 'Multi-model Support', 'Terminal & IDE'],
                installCommand: 'cargo install amp',
                startupCommand: 'amp',
                versionCheckCommand: 'amp --version',
                updateCommand: 'cargo install amp --force',
                logoUrl: 'https://amp.rs/images/logo.svg'
            },

    {
                id: 'roo-code',
                command: 'roo',
                displayName: 'Roo Code',
                description: 'Roo Code is an AI coding assistant that helps developers write better code faster. It provides intelligent suggestions and code completions.',
                themeColor: '#8B5CF6',
                icon: 'visualstudiocode',
                website: 'https://roo.dev',
                docsUrl: 'https://roo.dev/docs',
                category: 'ai_agent',
                usedFor: ['ai', 'coding', 'ide', 'autocomplete'],
                capabilities: ['Smart Completions', 'Code Analysis', 'IDE Integration'],
                installCommand: 'curl -fsSL https://raw.githubusercontent.com/RooCodeInc/Roo-Code/main/apps/cli/install.sh | sh',
                startupCommand: 'roo',
                versionCheckCommand: 'roo --version',
                updateCommand: 'curl -fsSL https://raw.githubusercontent.com/RooCodeInc/Roo-Code/main/apps/cli/install.sh | sh',
                logoUrl: 'https://raw.githubusercontent.com/RooCodeInc/Roo-Code/main/assets/icons/icon.png'
            },

    {
                id: 'cline',
                command: 'cline',
                displayName: 'Cline',
                description: 'Cline is an autonomous coding agent that lives in your IDE. It can create and edit files, run commands, and use the browser to complete complex tasks.',
                themeColor: '#EC4899',
                icon: 'visualstudiocode',
                website: 'https://github.com/cline/cline',
                docsUrl: 'https://github.com/cline/cline',
                category: 'ai_agent',
                usedFor: ['ai', 'coding', 'ide', 'agentic-flow'],
                capabilities: ['Autonomous Agent', 'File Editing', 'Browser Control'],
                installCommand: 'npm install -g cline',
                startupCommand: 'cline',
                versionCheckCommand: 'cline --version',
                updateCommand: 'npm install -g cline',
                logoUrl: 'https://raw.githubusercontent.com/cline/cline/main/assets/icons/icon.png'
            },

    {
                id: 'kilo-code',
                command: 'kilocode',
                displayName: 'Kilo Code',
                description: 'Kilo Code is an AI coding assistant focused on helping developers write clean, efficient code with intelligent suggestions.',
                themeColor: '#06B6D4',
                icon: 'gnubash',
                website: 'https://kilocode.ai',
                docsUrl: 'https://kilocode.ai/docs',
                category: 'ai_agent',
                usedFor: ['ai', 'coding', 'terminal', 'efficiency'],
                capabilities: ['Clean Code', 'Efficiency Focus', 'Smart Suggestions'],
                alternateCommands: ['kilo'],
                installCommand: 'npm install -g @kilocode/cli',
                startupCommand: 'kilocode',
                versionCheckCommand: 'kilocode --version',
                updateCommand: 'npm update -g @kilocode/cli',
                logoUrl: 'https://kilo.ai/favicon.ico'
            }
]
